plugin: amazon.aws.aws_ec2

regions:
  - ap-southeast-1

filters:
  instance-state-name: running
  "tag:Role": "portal"
  "tag:Name": "*p2-soar*"

hostnames:
  - tag:Name
  - private-ip-address
  - instance-id

compose:
  ansible_host: instance_id
  ansible_connection: "'amazon.aws.aws_ssm'"
  ansible_aws_ssm_region: "'ap-southeast-1'"
  ansible_aws_ssm_bucket_name: "'p2-soar-monitor-ansible-ssm-temp'"
  ansible_shell_type: "'sh'"
  ansible_user: "'ssm-user'"
  ansible_python_interpreter: "'/usr/bin/python3'"

keyed_groups:
  - key: tags.Role
    prefix: role

groups:
  portal: tags.Role == 'portal'
