/**
 * SOAR Portal — app.js
 * ====================
 * Authentication: AWS Cognito PKCE OAuth2
 * API: API Gateway (Cognito JWT Authorizer)
 * Approval: Step Functions TaskToken callback via /callback endpoint
 */

// ─── Config (loaded from config.json generated by Terraform) ────────────────
let CFG = {
    API_GATEWAY_URL:    '',
    INCIDENTS_API_URL:  '',
    CALLBACK_API_URL:   '',
    COGNITO_DOMAIN:     '',
    COGNITO_CLIENT_ID:  '',
    COGNITO_REDIRECT_URI: '',
    COGNITO_LOGOUT_URI:   '',
};

// ─── State ───────────────────────────────────────────────────────────────────
let incidents = [];
let refreshTimer = null;
let currentIncident = null;
let pendingDecision = null; // 'approve' | 'reject'

// ─── DOM refs ─────────────────────────────────────────────────────────────────
const loginContainer     = document.getElementById('login-container');
const dashboardContainer = document.getElementById('dashboard-container');
const cognitoLoginBtn    = document.getElementById('cognito-login-btn');
const logoutBtn          = document.getElementById('logout-btn');
const userDisplay        = document.getElementById('user-display');
const userGroupBadge     = document.getElementById('user-group-badge');
const tbody              = document.getElementById('incidents-body');
const approveModal       = document.getElementById('approve-modal');
const modalTitle         = document.getElementById('modal-title');
const modalDescription   = document.getElementById('modal-description');
const modalDetails       = document.getElementById('modal-details');
const cancelBtn          = document.getElementById('cancel-btn');
const confirmBtn         = document.getElementById('confirm-btn');
const rejectConfirmBtn   = document.getElementById('reject-confirm-btn');
const toast              = document.getElementById('toast');
const refreshBtn         = document.getElementById('refresh-btn');
const lastRefresh        = document.getElementById('last-refresh');
const loginError         = document.getElementById('login-error');

// ═══════════════════════════════════════════════════════════════════════════════
// CONFIG LOADER
// ═══════════════════════════════════════════════════════════════════════════════
async function loadConfig() {
    const res = await fetch('config.json', { cache: 'no-store' });
    if (!res.ok) throw new Error('Cannot load config.json — run terraform apply first');
    const cfg = await res.json();
    CFG = { ...CFG, ...cfg };
    console.log('[SOAR] Config loaded:', { ...CFG, COGNITO_CLIENT_ID: '***' });
}

// ═══════════════════════════════════════════════════════════════════════════════
// COGNITO PKCE AUTH
// ═══════════════════════════════════════════════════════════════════════════════

/** Generate crypto-safe random string for PKCE */
function generateRandom(len = 64) {
    const array = new Uint8Array(len);
    crypto.getRandomValues(array);
    return Array.from(array, b => ('0' + b.toString(16)).slice(-2)).join('');
}

/** SHA-256 → Base64URL (for PKCE code_challenge) */
async function sha256Base64Url(plain) {
    const encoded = new TextEncoder().encode(plain);
    const hash = await crypto.subtle.digest('SHA-256', encoded);
    return btoa(String.fromCharCode(...new Uint8Array(hash)))
        .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/** Initiate Cognito login — generate PKCE, redirect to Hosted UI */
async function initiateLogin() {
    try {
        await loadConfig();
    } catch (e) {
        showLoginError('Cannot load config.json. Make sure Terraform has been applied.');
        return;
    }

    if (!CFG.COGNITO_DOMAIN || !CFG.COGNITO_CLIENT_ID) {
        showLoginError('Cognito is not configured. Run terraform apply in monitor-account.');
        return;
    }

    const codeVerifier  = generateRandom(64);
    const codeChallenge = await sha256Base64Url(codeVerifier);
    const state         = generateRandom(16);

    // Persist for callback.html
    sessionStorage.setItem('pkce_code_verifier', codeVerifier);
    sessionStorage.setItem('oauth_state', state);

    const params = new URLSearchParams({
        response_type: 'code',
        client_id:     CFG.COGNITO_CLIENT_ID,
        redirect_uri:  CFG.COGNITO_REDIRECT_URI,
        scope:         'email openid profile',
        state:         state,
        code_challenge:        codeChallenge,
        code_challenge_method: 'S256',
    });

    window.location.href = `${CFG.COGNITO_DOMAIN}/oauth2/authorize?${params}`;
}

/** Check if user is already authenticated (tokens in sessionStorage) */
function isAuthenticated() {
    const token = sessionStorage.getItem('id_token');
    if (!token) return false;
    try {
        const payload = JSON.parse(atob(token.split('.')[1]));
        // Check token expiry (exp is in seconds)
        if (payload.exp && Date.now() / 1000 > payload.exp) {
            clearSession();
            return false;
        }
        return true;
    } catch {
        return false;
    }
}

function clearSession() {
    ['id_token', 'access_token', 'refresh_token', 'user_email', 'user_groups',
     'pkce_code_verifier', 'oauth_state'].forEach(k => sessionStorage.removeItem(k));
}

function getIdToken() {
    return sessionStorage.getItem('id_token') || '';
}

function getUserEmail() {
    return sessionStorage.getItem('user_email') || 'Analyst';
}

function getUserGroups() {
    try { return JSON.parse(sessionStorage.getItem('user_groups') || '[]'); }
    catch { return []; }
}

// ═══════════════════════════════════════════════════════════════════════════════
// AUTH-AWARE FETCH
// ═══════════════════════════════════════════════════════════════════════════════
async function apiFetch(url, options = {}) {
    const token = getIdToken();
    const headers = {
        'Content-Type': 'application/json',
        ...(token ? { 'Authorization': `Bearer ${token}` } : {}),
        ...(options.headers || {}),
    };
    return fetch(url, { ...options, headers });
}

// ═══════════════════════════════════════════════════════════════════════════════
// INIT — runs on page load
// ═══════════════════════════════════════════════════════════════════════════════
(async function init() {
    try {
        await loadConfig();
    } catch (e) {
        console.warn('[SOAR] Config not loaded on init:', e.message);
    }

    if (isAuthenticated()) {
        enterDashboard();
    } else {
        showLogin();
    }
})();

// ─── Login button ─────────────────────────────────────────────────────────────
cognitoLoginBtn.addEventListener('click', initiateLogin);

// ─── Logout ──────────────────────────────────────────────────────────────────
logoutBtn.addEventListener('click', () => {
    stopAutoRefresh();
    const logoutUrl = CFG.COGNITO_DOMAIN
        ? `${CFG.COGNITO_DOMAIN}/logout?client_id=${CFG.COGNITO_CLIENT_ID}&logout_uri=${encodeURIComponent(CFG.COGNITO_LOGOUT_URI || window.location.href)}`
        : null;
    clearSession();
    if (logoutUrl) {
        window.location.href = logoutUrl;
    } else {
        showLogin();
    }
});

// ─── Show / hide screens ─────────────────────────────────────────────────────
function showLogin() {
    loginContainer.classList.remove('hidden');
    dashboardContainer.classList.add('hidden');
}

async function enterDashboard() {
    loginContainer.classList.add('hidden');
    dashboardContainer.classList.remove('hidden');

    // Fill user info
    userDisplay.textContent = getUserEmail();
    const groups = getUserGroups();
    userGroupBadge.textContent = groups.length > 0 ? groups[0] : 'Viewer';

    renderSettings();
    await fetchIncidents();
    startAutoRefresh();
}

function showLoginError(msg) {
    loginError.textContent = msg;
    loginError.classList.remove('hidden');
}

// ═══════════════════════════════════════════════════════════════════════════════
// INCIDENT FETCH & RENDER
// ═══════════════════════════════════════════════════════════════════════════════
async function fetchIncidents({ silent = false } = {}) {
    if (!CFG.INCIDENTS_API_URL) {
        incidents = [];
        renderTable();
        if (!silent) showToast('Incidents API not configured. Run terraform apply.', true);
        return;
    }

    showLoadingState(true);

    try {
        const res = await apiFetch(CFG.INCIDENTS_API_URL, { cache: 'no-store' });

        if (res.status === 401) {
            showToast('Session expired. Please login again.', true);
            clearSession();
            showLogin();
            return;
        }

        const data = await res.json();
        if (!res.ok) throw new Error(data.error || 'Could not fetch incidents');

        incidents = Array.isArray(data.incidents) ? data.incidents.map(normalizeIncident) : [];
        renderTable();
        lastRefresh.textContent = `Updated ${new Date().toLocaleTimeString()}`;
        if (!silent) showToast(`Loaded ${incidents.length} incident(s).`);
    } catch (err) {
        if (!silent) showToast(`Error: ${err.message}`, true);
    } finally {
        showLoadingState(false);
    }
}

function showLoadingState(loading) {
    document.getElementById('loading-state').classList.toggle('hidden', !loading);
    document.getElementById('incidents-table').classList.toggle('hidden', loading);
}

function startAutoRefresh() {
    stopAutoRefresh();
    refreshTimer = setInterval(() => fetchIncidents({ silent: true }), 30000);
}

function stopAutoRefresh() {
    if (refreshTimer) clearInterval(refreshTimer);
    refreshTimer = null;
}

function normalizeIncident(inc) {
    const status = inc.incident_status || inc.status || 'Pending Approval';
    const action = inc.action_type || inc.remediation_action || inc.recommended_action || 'block_ip';
    return {
        id:        inc.incident_id || inc.id || 'unknown',
        severity:  inc.severity || 'High',
        summary:   inc.summary || inc.incident_title || inc.message || 'Elastic SIEM alert received',
        action,
        target:    inc.target || inc.source_ip || inc.destination_ip || 'unknown',
        status:    status.toLowerCase().replace(/\s+/g, '_'),
        timestamp: inc.timestamp || inc.updated_at || '',
        hasToken:  !!inc.task_token,  // has SF TaskToken = waiting in SF
    };
}

function escapeHtml(v) {
    return String(v ?? '').replace(/[&<>"']/g, c => ({
        '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'
    }[c]));
}

// ─── Render table ─────────────────────────────────────────────────────────────
function renderTable() {
    tbody.innerHTML = '';
    const tbl         = document.getElementById('incidents-table');
    const empty       = document.getElementById('empty-state');
    const badge       = document.getElementById('pending-actions-badge');
    const mTotal      = document.getElementById('metric-total');
    const mCritical   = document.getElementById('metric-critical');
    const mResolved   = document.getElementById('metric-mitigations');
    const mPending    = document.getElementById('metric-pending');

    const criticalCount = incidents.filter(i => i.severity.toLowerCase() === 'critical').length;
    const resolvedCount = incidents.filter(i => i.status === 'resolved').length;
    const pendingCount  = incidents.filter(i => i.status === 'pending_approval').length;

    mTotal.textContent    = incidents.length;
    mCritical.textContent = criticalCount;
    mResolved.textContent = resolvedCount;
    mPending.textContent  = pendingCount;

    if (incidents.length === 0) {
        tbl.classList.add('hidden');
        empty.classList.remove('hidden');
        badge.textContent = '0 Pending Actions';
        badge.classList.remove('pulse-red');
        badge.style.background = 'var(--success)';
        return;
    }

    tbl.classList.remove('hidden');
    empty.classList.add('hidden');

    incidents.forEach(inc => {
        const tr = document.createElement('tr');
        const sevClass = inc.severity.toLowerCase() === 'critical' ? 'critical' : 'high';

        let statusClass = 'pending', statusText = 'Pending Approval';
        if (inc.status === 'resolved')      { statusClass = 'resolved';  statusText = 'Resolved'; }
        else if (inc.status === 'rejected') { statusClass = 'rejected';  statusText = 'Rejected'; }
        else if (inc.status === 'timed_out'){ statusClass = 'rejected';  statusText = 'Timed Out'; }

        const isPending  = inc.status === 'pending_approval';
        const isDone     = ['resolved', 'rejected', 'timed_out'].includes(inc.status);

        let approvalHTML = '';
        if (isPending) {
            approvalHTML = `
                <div style="display:flex; gap:8px;">
                    <button class="btn-primary btn-small approve-trigger" data-id="${escapeHtml(inc.id)}">✅ Approve</button>
                    <button class="btn-danger btn-small reject-trigger" data-id="${escapeHtml(inc.id)}">❌ Reject</button>
                </div>`;
        } else if (inc.status === 'rejected') {
            approvalHTML = `<span style="color:var(--danger); font-size:0.85rem;">❌ Rejected</span>`;
        } else if (isDone) {
            approvalHTML = `<span style="color:var(--accent); font-size:0.85rem;">✅ Done</span>`;
        } else {
            approvalHTML = `<span style="color:var(--text-muted); font-size:0.85rem;">–</span>`;
        }

        tr.innerHTML = `
            <td><strong style="font-family:var(--font-mono); font-size:0.85rem;">${escapeHtml(inc.id)}</strong></td>
            <td><span class="badge ${sevClass}">${escapeHtml(inc.severity)}</span></td>
            <td style="max-width:280px; word-break:break-word;">${escapeHtml(inc.summary)}</td>
            <td><code>${escapeHtml(inc.action)}</code></td>
            <td><code style="font-size:0.8rem;">${escapeHtml(inc.target)}</code></td>
            <td><span class="badge ${statusClass}">${statusText}</span></td>
            <td>${approvalHTML}</td>`;
        tbody.appendChild(tr);
    });

    // Badge update
    if (pendingCount > 0) {
        badge.textContent = `${pendingCount} Pending Actions`;
        badge.classList.add('pulse-red');
        badge.style.background = 'var(--danger)';
    } else {
        badge.textContent = '0 Pending Actions';
        badge.classList.remove('pulse-red');
        badge.style.background = 'var(--success, #10b981)';
    }

    // Attach button events
    document.querySelectorAll('.approve-trigger').forEach(btn =>
        btn.addEventListener('click', e => openModal(e.target.dataset.id, 'approve')));
    document.querySelectorAll('.reject-trigger').forEach(btn =>
        btn.addEventListener('click', e => openModal(e.target.dataset.id, 'reject')));
}

// ═══════════════════════════════════════════════════════════════════════════════
// SIDEBAR NAV
// ═══════════════════════════════════════════════════════════════════════════════
document.querySelectorAll('#sidebar-nav a').forEach(link => {
    link.addEventListener('click', e => {
        e.preventDefault();
        document.querySelectorAll('#sidebar-nav a').forEach(l => l.classList.remove('active'));
        e.target.classList.add('active');
        document.querySelectorAll('.view-section').forEach(v => {
            v.classList.add('hidden');
            v.classList.remove('active');
        });
        const target = document.getElementById(e.target.dataset.target);
        if (target) { target.classList.remove('hidden'); target.classList.add('active'); }
    });
});

// ═══════════════════════════════════════════════════════════════════════════════
// MODAL — Approve / Reject
// ═══════════════════════════════════════════════════════════════════════════════
function openModal(id, decision) {
    currentIncident  = incidents.find(i => i.id === id);
    pendingDecision  = decision;
    if (!currentIncident) return;

    if (decision === 'approve') {
        modalTitle.textContent = '✅ Approve Remediation';
        modalDescription.textContent =
            `Execute "${currentIncident.action}" on target "${currentIncident.target}" for incident ${currentIncident.id}?`;
        confirmBtn.textContent  = '✅ Confirm & Execute';
        confirmBtn.style.display = '';
        rejectConfirmBtn.style.display = 'none';
    } else {
        modalTitle.textContent = '❌ Reject Incident';
        modalDescription.textContent =
            `Reject remediation for incident ${currentIncident.id}? This will record a rejection in the audit log.`;
        confirmBtn.style.display = 'none';
        rejectConfirmBtn.style.display = '';
    }

    modalDetails.textContent = JSON.stringify({
        incident_id: currentIncident.id,
        action_type: currentIncident.action,
        target:      currentIncident.target,
    }, null, 2);

    approveModal.classList.remove('hidden');
}

cancelBtn.addEventListener('click', closeModal);
approveModal.addEventListener('click', e => { if (e.target === approveModal) closeModal(); });

function closeModal() {
    approveModal.classList.add('hidden');
    currentIncident = null;
    pendingDecision = null;
    confirmBtn.textContent  = '✅ Approve & Execute';
    confirmBtn.disabled     = false;
    rejectConfirmBtn.disabled = false;
}

// Confirm Approve
confirmBtn.addEventListener('click', () => executeDecision('approved'));

// Confirm Reject
rejectConfirmBtn.addEventListener('click', () => executeDecision('rejected'));

async function executeDecision(decision) {
    if (!currentIncident) return;

    const btn = decision === 'approved' ? confirmBtn : rejectConfirmBtn;
    btn.textContent = decision === 'approved' ? 'Executing...' : 'Rejecting...';
    btn.disabled = true;

    try {
        if (!CFG.CALLBACK_API_URL) {
            // Fallback: no SF callback URL, use legacy remediation endpoint
            await legacyRemediate(decision);
        } else {
            await sfnCallback(decision);
        }
    } catch (err) {
        showToast(`Error: ${err.message}`, true);
    } finally {
        closeModal();
        await fetchIncidents({ silent: true });
    }
}

/** Step Functions callback — sends decision to /callback endpoint */
async function sfnCallback(decision) {
    const payload = {
        incident_id: currentIncident.id,
        decision:    decision,  // 'approved' | 'rejected'
    };

    const res = await apiFetch(CFG.CALLBACK_API_URL, {
        method: 'POST',
        body:   JSON.stringify(payload),
    });
    const data = await res.json();

    if (!res.ok) {
        // 409 = no task token (incident not in SF WaitForApproval state)
        if (res.status === 409) {
            showToast(`ℹ️ ${data.error}`, false);
        } else {
            throw new Error(data.error || `API error ${res.status}`);
        }
    } else {
        const verb = decision === 'approved' ? 'approved ✅' : 'rejected ❌';
        showToast(`Incident ${currentIncident.id} ${verb} — Step Functions resuming`);
    }
}

/** Legacy fallback for incidents without SF task token */
async function legacyRemediate(decision) {
    if (!CFG.API_GATEWAY_URL) {
        showToast('No API configured. Terraform apply required.', true);
        return;
    }

    const action = decision === 'approved' ? currentIncident.action : 'reject';
    const res = await apiFetch(CFG.API_GATEWAY_URL, {
        method: 'POST',
        body:   JSON.stringify({
            incident_id: currentIncident.id,
            action_type: action,
            target:      currentIncident.target,
        }),
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || 'API Error');
    showToast(`Success: ${data.message || 'Action executed'}`);
}

// ═══════════════════════════════════════════════════════════════════════════════
// SETTINGS VIEW
// ═══════════════════════════════════════════════════════════════════════════════
function renderSettings() {
    const el = document.getElementById('settings-body');
    el.innerHTML = `
        <table style="width:100%; border-collapse:collapse;">
            <tbody>
                ${row('User',             getUserEmail())}
                ${row('Groups',           getUserGroups().join(', ') || 'None')}
                ${row('Incidents API',    CFG.INCIDENTS_API_URL || '—')}
                ${row('Callback API',     CFG.CALLBACK_API_URL  || '—')}
                ${row('Cognito Domain',   CFG.COGNITO_DOMAIN    || '—')}
                ${row('Client ID',        CFG.COGNITO_CLIENT_ID ? '***' + CFG.COGNITO_CLIENT_ID.slice(-6) : '—')}
                ${row('Session Expires',  getTokenExpiry())}
            </tbody>
        </table>`;
}

function row(label, value) {
    return `<tr>
        <td style="padding:10px 16px; color:var(--text-muted); font-size:0.9rem; border-bottom:1px solid var(--panel-border); width:200px;">${label}</td>
        <td style="padding:10px 16px; font-family:var(--font-mono); font-size:0.85rem; border-bottom:1px solid var(--panel-border); word-break:break-all;">${escapeHtml(value)}</td>
    </tr>`;
}

function getTokenExpiry() {
    const token = sessionStorage.getItem('id_token');
    if (!token) return '—';
    try {
        const p = JSON.parse(atob(token.split('.')[1]));
        return p.exp ? new Date(p.exp * 1000).toLocaleString() : '—';
    } catch { return '—'; }
}

// ═══════════════════════════════════════════════════════════════════════════════
// REFRESH BUTTON
// ═══════════════════════════════════════════════════════════════════════════════
refreshBtn.addEventListener('click', async () => {
    showToast('Refreshing...');
    await fetchIncidents();
});

// ═══════════════════════════════════════════════════════════════════════════════
// TOAST
// ═══════════════════════════════════════════════════════════════════════════════
function showToast(message, isError = false) {
    toast.textContent = message;
    toast.style.borderColor = isError ? 'var(--danger)' : 'var(--accent)';
    toast.classList.remove('hidden');
    setTimeout(() => toast.classList.add('hidden'), 4000);
}
